server:
  port: 8080
  tomcat.uri-encoding: UTF-8
https:
  port: 443
  ssl:
    key-store: classpath:www.xkhome.online.pfx
    key-store-password: 82Qb2nwV
    key-password: Q99Jejea
    key-store-type: PKCS12
    key-alias: your.alias
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.sungang.model
  mapperLocations: classpath:mapper/*.xml
web.upload-path: /home/sungang/server/single-webchat-server/static/code/

spring:
    mvc.static-path-pattern: /image/**
    resources.static-locations: file:${web.upload-path}

    http:
      encoding.force : true
      encoding.charset: UTF-8
      encoding.enabled: true
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://39.104.116.127:3306/single-server?useUnicode=true&allowMultiQueries=true&autoReconnect=true
          username: root
          password: root
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
logging:
  file: /home/sungang/server/single-webchat-server/log/server.log
#httpclient config
http:
   #最大连接数
   maxTotal : 100
   #并发数
   defaultMaxPerRoute : 20
   #创建连接的最长时间
   connectTimeout: 1000
   #从连接池中获取到连接的最长时间
   connectionRequestTimeout: 500
   #数据传输的最长时间
   socketTimeout: 10000
   #提交请求前测试连接是否可用
   staleConnectionCheckEnabled: true
# webchat
webchat:
    appId: wx2892a6e1cb385d1a
    appsecret: a4e0cf9889e5ad7449a79b61397ca150
    openIdUrl: https://api.weixin.qq.com/sns/jscode2session
    access_token_url: https://api.weixin.qq.com/cgi-bin/token
    access_token_path: access_token.txt




